### ISSUE TITLE
Large object models cause request issues when M409 and rr_model used at the same time

### ISSUE THREAD

**Issue by T3P3** [dc42/RepRapFirmware#995]
503 errors occur in DWC running duet2 ethernet with a large Object Model, when a PanelDue is also connected.

The proposed solution it to ensure only one of the channels can query the OM at one time.

**Comment by dc42** [comment]
Added a mutex so that PanelDue and HTTP don't generate an object model response concurrently. Still need to delay generating that response if insufficient buffer space available.

**Comment by dc42** [comment]
Fixed in 3.5-dev.

**Comment by AlexKid007** [comment]
Hi @dc42,

today I updated my Duet2 Ethernet to Version 3.5.2. I still get disconnect and reconnect messages very frequently on web interface console page.
 
![image](https://github.com/user-attachments/assets/2f47c41f-8f51-4855-93a8-bdc6c9a548bc)
